# Flask configuration
FLASK_DEBUG = True
FLASK_USE_RELOADER = True

FLASK_HOST = "0.0.0.0"
FLASK_PORT = 42488

# RESTful API configuration
API_VERSION = "v1"
API_BASE_URL = f"/sprinkler/{API_VERSION}/api"

API_CONTROL_ENDPOINT = "/control"
API_SCHEDULE_ENDPOINT = "/schedule"

API_CONTROL_URL = f"{API_BASE_URL}{API_CONTROL_ENDPOINT}"
API_SCHEDULE_URL = f"{API_BASE_URL}{API_SCHEDULE_ENDPOINT}"

# SocketIO configuration
SOCKETIO_VERSION = "v1"
SOCKETIO_BASE_URL = f"/sprinkler/{SOCKETIO_VERSION}/socketio"

SOCKETIO_UPDATE_ENDPOINT = "/update"

SOCKETIO_UPDATE_URL = f"{SOCKETIO_BASE_URL}{SOCKETIO_UPDATE_ENDPOINT}"

CONTROL = [
    f"{API_CONTROL_URL}/",
    f"{API_CONTROL_URL}/<string:relay_id>",
]

SCHEDULE_CONTROL = [f"{API_SCHEDULE_URL}/", f"{API_SCHEDULE_URL}/<string:schedule_id>"]

ACTIVE_SCHEDULE_CONTROL = [
    f"{API_SCHEDULE_URL}/active",
    f"{API_SCHEDULE_URL}/active/<string:schedule_id>",
]
